github actions用のコード修正

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -6,28 +6,45 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
+    env:
+      BASE_PATH: "/${{ github.event.repository.name }}"
 
     steps:
     - uses: actions/checkout@v3.5.2
 
+    - name: Detect package manager
+      id: detect-package-manager
+      run: |
+        if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+          echo "manager=yarn" >> $GITHUB_ENV
+          echo "command=install" >> $GITHUB_ENV
+          echo "runner=yarn" >> $GITHUB_ENV
+          exit 0
+        elif [ -f "${{ github.workspace }}/package.json" ]; then
+          echo "manager=npm" >> $GITHUB_ENV
+          echo "command=ci" >> $GITHUB_ENV
+          echo "runner=npx --no-install" >> $GITHUB_ENV
+          exit 0
+        else
+          echo "Unable to determine package manager"
+          exit 1
+        fi
+
     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
-        node-version: 16
+        node-version: "16"
+        cache: ${{ env.manager }}
 
     - name: Install dependencies
-      run: npm ci
-
-    # - name: Run tests
-    #   run: npm test
+      run: ${{ env.manager }} ${{ env.command }}
 
     - name: Build
-      run: npm run build
+      run: ${{ env.runner }} npm run build
 
     - name: Export static pages
-      run: npm run export
+      run: ${{ env.runner }} npm run export
 
     - name: Deploy to S3
       uses: jakejarvis/s3-sync-action@master
